# fly.toml app configuration file generated for datingappmanu on 2023-04-30T23:57:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappmanu"
primary_region = "otp"

[build]
  image = "cristutiu/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "468697668175842"
  CloudinarySettings__CloudName = "djva03kbf"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true